"""add email and full_name to users

Revision ID: 807992cb6a9c
Revises: c1a4d8e9f2b3
Create Date: 2026-09-17 15:06:57.474947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807992cb6a9c'
down_revision: Union[str, Sequence[str], None] = 'c1a4d8e9f2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('room_players_room_id_fkey'), 'room_players', type_='foreignkey')
    op.create_foreign_key(None, 'room_players', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(op.f('submissions_room_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'rooms', ['room_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'email')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_room_id_fkey'), 'submissions', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'room_players', type_='foreignkey')
    op.create_foreign_key(op.f('room_players_room_id_fkey'), 'room_players', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
