"""Enforce one membership and one answer per player and question."""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "943c0ad1f6e2"
down_revision: Union[str, Sequence[str], None] = "807992cb6a9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Earlier installations may have applied the old 50-character email migration.
    op.alter_column("users", "email", existing_type=sa.String(length=50), type_=sa.String(length=254))
    # Repair databases that already ran the earlier autogenerated migration, which
    # created these constraints under PostgreSQL's default names.
    inspector = sa.inspect(op.get_bind())
    for table_name, old_name, new_name in (
        ("room_players", "room_players_room_id_fkey", "fk_room_players_room_id_rooms"),
        ("submissions", "submissions_room_id_fkey", "fk_submissions_room_id_rooms"),
    ):
        names = {foreign_key["name"] for foreign_key in inspector.get_foreign_keys(table_name)}
        if old_name in names and new_name not in names:
            op.execute(
                sa.text(
                    f'ALTER TABLE "{table_name}" RENAME CONSTRAINT "{old_name}" TO "{new_name}"'
                )
            )

    # Keep the oldest rows before adding constraints to existing installations.
    op.execute(
        "DELETE FROM room_players AS duplicate USING room_players AS keeper "
        "WHERE duplicate.room_id = keeper.room_id AND duplicate.user_id = keeper.user_id "
        "AND duplicate.id > keeper.id"
    )
    op.execute(
        "DELETE FROM submissions AS duplicate USING submissions AS keeper "
        "WHERE duplicate.room_id = keeper.room_id AND duplicate.user_id = keeper.user_id "
        "AND duplicate.word_id = keeper.word_id AND duplicate.id > keeper.id"
    )
    op.execute(
        "UPDATE room_players AS player SET score = (SELECT COUNT(*) FROM submissions "
        "WHERE submissions.room_id = player.room_id AND submissions.user_id = player.user_id "
        "AND submissions.is_correct)"
    )
    op.create_unique_constraint(
        "uq_room_players_room_user", "room_players", ["room_id", "user_id"]
    )
    op.create_unique_constraint(
        "uq_submissions_room_user_word", "submissions", ["room_id", "user_id", "word_id"]
    )


def downgrade() -> None:
    op.drop_constraint("uq_submissions_room_user_word", "submissions", type_="unique")
    op.drop_constraint("uq_room_players_room_user", "room_players", type_="unique")
